# Generated by Django 4.2.5 on 2023-10-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deals_name', models.CharField(default='', max_length=50)),
                ('deals_image', models.ImageField(default='', upload_to='shop/deals')),
                ('deals_price', models.IntegerField(default=0)),
            ],
        ),
    ]
