# Generated by Django 4.2.5 on 2023-10-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_topdeals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopDeals',
            new_name='TopDeal',
        ),
    ]
