# Generated by Django 4.2.5 on 2023-10-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_topdeals_topdeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='topdeal',
            name='deals_desc',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.CharField(default='', max_length=300),
        ),
    ]
