# Generated by Django 4.2.5 on 2023-10-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(default='', max_length=5000)),
                ('name', models.CharField(default='', max_length=90)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=100)),
                ('zip_code', models.CharField(max_length=7)),
                ('city', models.CharField(default='', max_length=50)),
                ('mssg', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
