# Generated by Django 4.2.5 on 2023-10-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orders_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=10)),
                ('discount_price', models.IntegerField(default='100')),
                ('minimum_amount', models.IntegerField(default='100')),
            ],
        ),
    ]
