# Generated by Django 4.2.5 on 2023-10-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='minimum_amount',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_price',
            field=models.IntegerField(default='0'),
        ),
    ]
